name: EClean
version: ${version}
main: top.e404.eclean.EClean
api-version: 1.13
authors: [ 404E ]
commands:
  eclean:
    description: 插件主命令
    aliases:
      - ecl
permissions:
  eclean.admin:
    default: op
    description: 允许使用插件管理指令